name       : python-kitchen
version    : 1.2.5
release    : 1
source     :
    - https://pypi.python.org/packages/14/3c/eb027400d34ed066d882d4cbbcb9b84eb7e91a7be770dd6fecebc37ba91f/kitchen-1.2.5.tar.gz : af9fbb60f68cbdb2ead402beb8fa7c7edadbe2aa7b5a70138b7c4b0fa88153fd
license    : LGPL-2.0+
component  : programming.python
summary    : Kitchen contains a cornucopia of useful code
description: |
    We’ve all done it. In the process of writing a brand new application we’ve discovered that we need a little bit of code that we’ve invented before. Perhaps it’s something to handle unicode text. Perhaps it’s something to make a bit of python-2.5 code run on python-2.3. Whatever it is, it ends up being a tiny bit of code that seems too small to worry about pushing into its own module so it sits there, a part of your current project, waiting to be cut and pasted into your next project. And the next. And the next. And since that little bittybit of code proved so useful to you, it’s highly likely that it proved useful to someone else as well. Useful enough that they’ve written it and copy and pasted it over and over into each of their new projects.
    Well, no longer! Kitchen aims to pull these small snippets of code into a few python modules which you can import and use within your project. No more copy and paste! Now you can let someone else maintain and release these small snippets so that you can get on with your life.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
